### PR TITLE
Lower the bar for PRs

### PR DESCRIPTION
**Pull request by thetrentus**
Authorize 1 user to merge

### CODE REVIEW

**Comment by sau226** [comment]
Jenkins build started

**Comment by sau226** [comment]
Build complete. Successful

**Comment by sau226** [comment]
!approve

[Approved with PullApprove](https://pullapprove.com/thetrentus/Reddit-Test/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=thetrentus/Reddit-Test)

**Comment by thetrentus** [comment]
This looks mergeable

**Comment by thetrentus** [comment]
!approve

[Approved with PullApprove](https://pullapprove.com/thetrentus/Reddit-Test/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=thetrentus/Reddit-Test)

**Pull request merged**
