### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by thetrentus**
This copy isn't archived. This PR fixes that issue

### CODE REVIEW

**Comment by sau226** [comment]
Jenkins build starting

**Comment by thetrentus-review** [comment]
Build complete. Approving

Executing !approve command

**Review by sau226 — APPROVED** [review]
This commit looks fine

Using automated reply bot

**Comment by thetrentus** [comment]
!approve

**Comment by thetrentus** [comment]
!approve

[Approved with PullApprove](https://pullapprove.com/thetrentus/Reddit-Test1/pull-request/1/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=thetrentus/Reddit-Test1)

**Pull request merged**
