### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by thetrentus**
Fixing reddit files.

### CODE REVIEW

**Comment by thetrentus** [comment]
Bot !trigger/review

**Comment by sau226** [comment]
Reviewing. Build successful

**Comment by thetrentus-review** [comment]
Jenkins build complete. Successful

Approval: !approve

**Comment by sau226** [comment]
!approve

[Approved with PullApprove](https://pullapprove.com/thetrentus/Reddit-Test/pull-request/2/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=thetrentus/Reddit-Test)

**Comment by thetrentus** [comment]
This looks fine

**Comment by thetrentus** [comment]
!approve

[Approved with PullApprove](https://pullapprove.com/thetrentus/Reddit-Test/pull-request/2/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=thetrentus/Reddit-Test)

**Pull request merged**
